### PR TITLE
selenium-standalone in the docker-image

### PR DESCRIPTION
**Pull request by yvesh**
Have selenium install in the docker image, this way you don't need to install it (with a absurd long version string), every time you run the system tests.

### CODE REVIEW

**Comment by zero-24** [comment]
we might install netcat here too?

**Comment by zero-24** [comment]
so we can do `while ! nc -z localhost 4444; do sleep 2; done` to make sure the server is started correclty

**Comment by wilsonge** [comment]
The selenium version was coming in direct from our composer repo because (admittedly a while ago now - I was playing around with weblinks in september 2019 https://github.com/joomla-extensions/weblinks/commits/fix-weblinks-tests) the latest version of selenium which moved to the W3C specification wasn't working in our linux browser versions.

**Comment by yvesh** [comment]
This is not the selenium-version from composer (which we as joomla-project maintained), but a npm one, we also use in j4-dev. At least locally for Tobias and me the latest version with the latest chrome has been working too.

**Comment by wilsonge** [comment]
So from the docs here doesn't look like we are using that https://github.com/joomla/joomla-cms/pull/25483 it was a simplicity thing for running locally.

**Comment by yvesh** [comment]
Not sure I can follow you George. We currently install it here in J4 for every run:
https://github.com/joomla/joomla-cms/blob/4.0-dev/tests/Codeception/drone-system-run.sh#L53

As an alternative to always use latest versions, we can hard-code these two versions (e.g. driver + chrome / chromium) in the image here itself. Would save some time and traffic.

**Comment by wilsonge** [comment]
🤦‍♂ so wait does that mean we aren't using the composer ones?

**Comment by yvesh** [comment]
No, not since the PR you mentioned.. The composer ones are totally outdated by now anyways and won't run with a recent chrome version.

**Pull request merged**
